# Generated by Django 5.2.1 on 2025-06-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specs_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('price_day', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('max_speed', models.IntegerField()),
                ('range', models.IntegerField()),
                ('wheels_size', models.IntegerField()),
                ('power', models.IntegerField()),
                ('battery_current', models.IntegerField()),
                ('main_img', models.URLField()),
                ('nav_photo', models.URLField()),
                ('landscape_img', models.URLField()),
                ('side_photo_left', models.URLField()),
                ('side_photo_right', models.URLField()),
                ('front_photo_view', models.URLField()),
                ('rear_photo_view', models.URLField()),
                ('top_photo_view', models.URLField()),
                ('drive_train_closeup_photo', models.URLField()),
                ('handlebar_controls_photo', models.URLField()),
                ('suspension_fork_photo', models.URLField()),
                ('wheel_tire_condition_photo', models.URLField()),
                ('serial_number_or_branding_photo', models.URLField()),
                ('battery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specs_types.batterytype')),
                ('brakes_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specs_types.brakestype')),
                ('engine_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specs_types.engineposition')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specs_types.status')),
            ],
        ),
    ]
