# Generated by Django 5.2.1 on 2025-07-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
