# Generated by Django 5.2.1 on 2025-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0002_alter_contactrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
