# Generated by Django 5.2.1 on 2025-07-21 07:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_title_blogpost_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='banner',
            new_name='banner_uk',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='banner_en',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='banner_ru',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
