# Generated by Django 5.2.1 on 2025-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_banner_blogpost_banner_uk_blogpost_banner_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='content_uk',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='title_uk',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(default='', max_length=250),
        ),
    ]
