# Generated by Django 5.2.1 on 2025-07-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_bike_drive_train_closeup_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bike')),
            ],
        ),
    ]
