# Generated by Django 5.2.1 on 2025-06-18 09:19

import backendApps.specs_types.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
            ],
            bases=(models.Model, backendApps.specs_types.models.LocalizedNameMixin),
        ),
        migrations.CreateModel(
            name='BrakesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
            ],
            bases=(models.Model, backendApps.specs_types.models.LocalizedNameMixin),
        ),
        migrations.CreateModel(
            name='EnginePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
            ],
            bases=(models.Model, backendApps.specs_types.models.LocalizedNameMixin),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
            ],
            bases=(models.Model, backendApps.specs_types.models.LocalizedNameMixin),
        ),
    ]
