# Generated by Django 5.2.1 on 2025-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
